# Generated by Django 4.1 on 2022-08-29 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill_type',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='名称')),
                ('description', models.CharField(default='', max_length=128, verbose_name='描述')),
                ('data_joined', models.DateTimeField(auto_now_add=True, verbose_name='category创建时间')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='category更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='名称')),
                ('description', models.CharField(default='', max_length=128, verbose_name='描述')),
                ('tagid', models.CharField(max_length=5, unique=True, verbose_name='标签id')),
                ('data_joined', models.DateTimeField(auto_now_add=True, verbose_name='tag创建时间')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='tag更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=32, verbose_name='todo名称')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='todo创建时间')),
                ('note', models.CharField(default='', max_length=128, verbose_name='todo备注')),
                ('finished', models.BooleanField(default=False, verbose_name='todo是否完成')),
                ('date_finished', models.DateTimeField(auto_now=True, verbose_name='todo结束时间')),
                ('typeid', models.SmallIntegerField(verbose_name='todo_type的id')),
            ],
        ),
        migrations.CreateModel(
            name='todo_type',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='todo类型名称')),
                ('color', models.CharField(default='', max_length=10, verbose_name='todo标签的颜色')),
            ],
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='收入')),
                ('note', models.CharField(default='', max_length=128, verbose_name='备注')),
                ('data_joined', models.DateTimeField(auto_now_add=True, verbose_name='bill创建时间')),
                ('billtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.bill_type', verbose_name='bill类型')),
            ],
        ),
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='文章名称')),
                ('short_description', models.CharField(max_length=512, verbose_name='文章简短描述')),
                ('tagid', models.CharField(max_length=100, verbose_name='文章标签')),
                ('save_path', models.SlugField(max_length=128, verbose_name='文章存储路径')),
                ('data_joined', models.DateTimeField(auto_now_add=True, verbose_name='article创建时间')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='article更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.category', verbose_name='文章类别id')),
            ],
        ),
    ]
